name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['^1.3.0-rc5']
        julia-arch: [x64]
        os: [ubuntu-latest, ubuntu-16.04, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Add registry
        run: |
          julia --project -e 'using Pkg; Pkg.Registry.status()'
          julia --project -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url = "https://github.com/Lyceum/LyceumRegistry.git"))'
          julia --project -e 'using Pkg; Pkg.Registry.status()'
          julia --project -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url = "https://github.com/JuliaRegistries/General.git"))'
          julia --project -e 'using Pkg; Pkg.Registry.status()'
        shell: bash
      - uses: julia-actions/julia-buildpkg@master
      - uses: julia-actions/julia-runtest@master
